apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-1.1.0
    cert-manager.io/issuer: vacation-planner-identity-issuer
  name: vacation-planner-identity
spec:
  gatewayClassName: nginx
  listeners:
  - hostname: planner.local.babosbird.com
    name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - hostname: planner.local.babosbird.com
    name: https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: vacation-planner-identity-tls-secret