apiVersion: v1
kind: Secret
metadata:
  name: vacation-planner-identity-secrets
  namespace: vacation-planner-identity
  labels:
    app: vacation-planner-identity
type: Opaque
data:
  AZURE_STORAGE_ACCOUNT_CONNECTION_STRING: ""
  AZURE_CLIENT_SECRET: ""
  SECRET_KEY: ""
