apiVersion: v1
kind: Secret
metadata:
  name: vacation-planner-mongodb-secrets
  namespace: vacation-planner-mongodb
  labels:
    app: vacation-planner-mongodb
type: Opaque
data:
  COSMOSDB_CONNECTION_STRING: ""
  SECRET_KEY: ""
