apiVersion: v1
kind: Secret
metadata:
  name: vacation-planner-mysql-secrets
  namespace: vacation-planner-mysql
  labels:
    app: vacation-planner-mysql
type: Opaque
data:
  MYSQL_PASSWORD: ""
  SECRET_KEY: ""
