apiVersion: v1
kind: Service
metadata:
  name: vacation-planner-mysql
  namespace: vacation-planner-mysql
  labels:
    app: vacation-planner-mysql
spec:
  type: ClusterIP
  selector:
    app: vacation-planner-mysql
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
