apiVersion: v1
kind: Secret
metadata:
  name: vacation-planner-blob-secrets
  namespace: vacation-planner-blob
  labels:
    app: vacation-planner-blob
type: Opaque
data:
  AZURE_STORAGE_ACCOUNT_CONNECTION_STRING: ""
  SECRET_KEY: ""
