apiVersion: v1
kind: Secret
metadata:
  name: vacation-planner-nosql-secrets
  namespace: vacation-planner-nosql
  labels:
    app: vacation-planner-nosql
type: Opaque
data:
  AZURECOSMOSDB_PRIMARY_KEY: ""
  FLASK_SECRET_KEY: ""
