apiVersion: v1
kind: Secret
metadata:
  name: vacation-planner-sql-secrets
  namespace: vacation-planner-sql
  labels:
    app: vacation-planner-sql
type: Opaque
data:
  SQL_PASSWORD: ""
  SECRET_KEY: ""
