apiVersion: v1
kind: ConfigMap
metadata:
  name: vacation-planner-identity-config
  namespace: vacation-planner-identity
  labels:
    app: vacation-planner-identity
data:
  CONTAINER_NAME: "activities"
  AZURE_CLIENT_ID: ""
  AZURE_TENANT_ID: ""
  AZURE_STORAGE_ACCOUNT_URL: ""
