apiVersion: v1
kind: Secret
metadata:
  name: vacation-planner-postgres-secrets
  namespace: vacation-planner-postgres
  labels:
    app: vacation-planner-postgres
type: Opaque
data:
  PG_PASSWORD: ""
  SECRET_KEY: ""
