apiVersion: v1
kind: Service
metadata:
  name: vacation-planner-nosql
  namespace: vacation-planner-nosql
  labels:
    app: vacation-planner-nosql
spec:
  type: ClusterIP
  selector:
    app: vacation-planner-nosql
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
